openapi: 3.0.1
info:
  title: Simple Web App API
  contact:
    name: Alexey Yatsevich
    url: https://github.com/MarshallBaby
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8080
    description: Generated server url
paths:
  /api/employees:
    get:
      tags:
        - employee-controller
      operationId: findEmployees
      parameters:
        - name: first-name
          in: query
          required: false
          schema:
            type: string
            default: ''
        - name: last-name
          in: query
          required: false
          schema:
            type: string
            default: ''
      responses:
        '200':
          description: Returns result Employee entity
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    put:
      tags:
        - employee-controller
      operationId: updateEmployee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        '200':
          description: Returns result Employee entity
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    post:
      tags:
        - employee-controller
      operationId: saveEmployee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
  /api/employees/{id}:
    get:
      tags:
        - employee-controller
      operationId: findEmployeeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      tags:
        - employee-controller
      operationId: deleteEmployeeById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Not Found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Internal Server Error
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    ErrorMessage:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        description:
          type: string
    Employee:
      type: object
      properties:
        employeeId:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        departmentId:
          type: integer
          format: int32
        jobTitle:
          type: string
        gender:
          type: string
          enum:
            - MALE
            - FEMALE
        age:
          minimum: 18
          type: integer
          format: int32
